# Generated by Django 4.2.4 on 2023-08-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_bar',
            field=models.CharField(default='', max_length=320),
        ),
    ]
