# Generated by Django 4.2.4 on 2023-08-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factapp', '0002_article_code_bar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
